language: php
php:
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache
git:
  depth: 3

before_script:
  - phpenv config-rm xdebug.ini
  - composer install
script:
  - phpdbg -qrr vendor/bin/phpunit
